debug: true

spring:
  application:
    name: Tunnel

endpoints:
  sensitive: false
  routes:
    enabled: true

zuul:
  host:
    socket-timeout-millis: 100000
    connect-timeout-millis: 20000
  routes:
    fuckup:
      path: /fuckup/**
      url: tunnel://fuckup.me
    httpbin:
      path: /httpbin/**
      url: http://httpbin.org

proxy:
  tunnel:
    sockets:
      httpbin:
        connCount: 5
        port: 2333


logging:
  level:
    ROOT: DEBUG



